#!/bin/sh -e
#
# Copyright (c) 2013-2020 Robert Nelson <robertcnelson@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

#Based off:
#https://github.com/beagleboard/meta-beagleboard/blob/master/meta-beagleboard-extras/recipes-support/usb-gadget/gadget-init/g-ether-load.sh

#  idVendor           0x1d6b Linux Foundation
#  idProduct          0x0104 Multifunction Composite Gadget
#  bcdDevice            4.04
#  bcdUSB               2.00

#######################################################################################################################
#######################################################################################################################
## Modified from:                                                                                                    ##
##    https://github.com/RobertCNelson/boot-scripts/blob/674bb55e34e94e3837f4f55790c7d1a52c9e149f/boot/am335x_evm.sh ##
## for the DORA project @ ASU                                                                                        ##
#######################################################################################################################
#######################################################################################################################
# Additional links that might be helpful for future modification:
#   https://stackoverflow.com/questions/44053344/g-multi-mode-mass-storage-ethernet-not-working-on-raspberry-pi-zero-w
#   http://trac.gateworks.com/wiki/linux/OTG
#   https://www.kernel.org/doc/html/v5.8/usb/gadget_configfs.html
#   https://www.kernel.org/doc/html/latest/usb/gadget_configfs.html
#   https://www.kernel.org/doc/Documentation/usb/gadget_serial.txt
#   https://stackoverflow.com/questions/33546269/how-can-beaglebone-black-be-used-as-mass-storage-device
#   https://developer.ridgerun.com/wiki/index.php/How_to_use_USB_CDC_ACM_and_MS_composite_Linux_gadget_driver
#   https://forum.beagleboard.org/t/usb-configfs-in-device-tree/29020
#########################################################################################################################

# Magic numbers pulled from the script used by the official Debian image
usb_idVendor="0x1d6b"
usb_idProduct="0x0104"
usb_bcdDevice="0x0404"
usb_bcdUSB="0x0200"
usb_serialnr="000000"
usb_product="Multi Gadget"
usb_iserialnumber="1234BBBK5678"
usb_imanufacturer="BeagleBoard.org"
usb_iproduct="BeagleBoneBlack"

# Load the stuff needed for configfs
modprobe libcomposite

# Set up our configfs filesystem
mount none /sys/kernel/config -t configfs

# Make a folder for our gadget
mkdir /sys/kernel/config/usb_gadget/g1
cd /sys/kernel/config/usb_gadget/g1

# Set up sode metadata
echo $usb_idProduct > idProduct
echo $usb_idVendor > idVendor

mkdir strings/0x409

echo $usb_iserialnumber > strings/0x409/serialnumber
echo $usb_imanufacturer > strings/0x409/manufacturer
echo $usb_product > strings/0x409/product

mkdir configs/c.1

echo 500 > configs/c.1/MaxPower

mkdir -p configs/c.1/strings/0x409
echo "BeagleBone Composite" > configs/c.1/strings/0x409/configuration

mkdir functions/acm.0
mkdir functions/ecm.0
mkdir functions/rndis.0
# mkdir functions/mass_storage.0

# mkdir functions/ecm.usb0
# ln -s functions/ecm.usb0 configs/c.1
# echo "62:6b:4f:45:ad:8f" > functions/ecm.0/host_addr

ln -s functions/rndis.0 configs/c.1
ln -s functions/acm.0 configs/c.1

# Turn it on
echo "musb-hdrc.0" > /sys/kernel/config/usb_gadget/g1/UDC

